MAIN_CATEGORY_NAME = "bebot"
MAIN_CHANNEL_NAME = "musiquita-jot"
PLAYLISTS_CHANNEL_NAME = "playlists"

NOW_PLAYING = "Escuchando:"
NOTHING_PLAYING = "Nada... Que aburrido."
PREV_BUTTON_LABEL = "Prev"
PLAY_STOP_BUTTON_LABEL = "Stop/Resume"
NEXT_BUTTON_LABEL = "Next"
QUEUE_BUTTON_LABEL = "Queue"
LEAVE_BUTTON_LABEL = "Leave"

QUEUE_NOTHING_PLAYING = "Tengo la cola vacia :("
QUEUE_CURRENT = "Ahora: %s"
QUEUE_PAGE_FOOTER = "Pagina %s/%s"
